### PR TITLE
fix: Mod view with no game install

### LINKED ISSUE #64: Mod tab throws error when opening it without a selected Titanfall2 install
Mod tab throws error when opening it without a selected Titanfall2 install. Instead it should simply show something like "No install found" or "No mods detected" or something along the lines.

### PR DESCRIPTION
**Pull request by Alystrasz**
Display a message on empty mods view instead of showing an error notification.
Closes #64.

##### Before

Capture d’écran de 2022-12-15 08-25-10

##### After

Capture d’écran de 2022-12-15 08-23-40

### CODE REVIEW

File: src-vue/src/plugins/store.ts [hunk 1]
```diff
@@ -245,12 +245,16 @@ export const store = createStore<FlightCoreStore>({
...
+                    // TODO discuss if we should delete this
+                    // If there's no other error case as "no install selected", I think we can get rid of it.
+                    /*
                     ElNotification({
                         title: 'Error',
                         message: error,
                         type: 'error',
                         position: 'bottom-right'
                     });
+                    */
```
Comment (GeckoEidechse) [inline src-vue/src/plugins/store.ts:257]: While unlikely in practice, there can be other error cases. E.g.: lack of mods directory or some incorrectly formatted JSON.

It might make more sense to do an if-guard to check if the install path is actually set, before calling the backend function ^^

**Review by GeckoEidechse — COMMENTED** [review]
Current implementation works on both Windows and Linux ^^

(though if-guard before calling backend would probably be preferred)

File: src-vue/src/plugins/store.ts (hunk 1 above)
Comment (Alystrasz) [reply src-vue/src/plugins/store.ts]: Reverted in 2f6f90ee0dcafb03853b9dd29f79c5c118dcd350

**Review by GeckoEidechse — APPROVED** [review]
Changes look good and code was (re-)confirmed working in testing on Linux ^^
