### PR TITLE
fix: Don't show deprecated mods

### LINKED ISSUE #307: Show when mod is marked deprecated in Thunderstore mod browser
Currently we don't show when a mod is deprecated in Thunderstore mod browser

image

### PR DESCRIPTION
**Pull request by Alystrasz**
Since we don't want users to install deprecated mods, these are not displayed by default on the Thunderstore mods view.

If users like to live dangerously, they still can activate deprecated mods display via a dedicated option in the settings; deprecated mods cards will then appear with a particular style.

##### Screenshots

Capture d’écran du 2023-06-07 22-12-09

image

---

Closes #307.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Wait, we already propagate deprecated flag to frontend? Thought I had to expose it first lol

Any way, PR is very much appreciated, taking a look in a sec ^^

File: src-vue/src/views/SettingsView.vue [hunk 1]
```diff
@@ -40,6 +40,18 @@
...
 
+                <div class="fc_parameter__panel">
+                    <h3>{{ $t('settings.show_deprecated_mods') }}</h3>
+                    <h6>
+                        {{ $t('settings.show_deprecated_mods_desc1') }}<br/>
+                        {{ $t('settings.show_deprecated_mods_desc2') }}
+                    </h6>
+                    <span>
+                        {{ $t('settings.show_deprecated_mods') }}
+                        <el-switch v-model="showDeprecatedMods"></el-switch>
```
Comment (GeckoEidechse) [inline src-vue/src/views/SettingsView.vue:51]: This value is not stored in persistent store which tbh I'd consider a feature and not a bug ^^

File: src-vue/src/i18n/lang/en.json [hunk 2]
```diff
@@ -106,6 +106,9 @@
         "enable_test_channels": "Enable testing release channels",
         "dev_mode_enabled_title": "Watch out!",
         "dev_mode_enabled_text": "Developer mode enabled.",
+        "show_deprecated_mods": "Show deprecated Thunderstore mods",
+        "show_deprecated_mods_desc1": "This allows you to see deprecated mods in the online mods collection.",
+        "show_deprecated_mods_desc2": "Watch out, such mods are usually deprecated for a good reason.",
```
Comment (GeckoEidechse) [inline src-vue/src/i18n/lang/en.json:111]: With weblate support added now we'll just add translations post merge which is fine ^^

**Review by GeckoEidechse — APPROVED** [review]
Confirmed working testing, thanks <3
