### PR TITLE
fix: Address regression around persistent store

### LINKED ISSUE #233: Storing persistence is broken
Tested on Linux rn and broken since at least `v1.10.1` of FlightCore.

Probably #176 that broke it.

### PR DESCRIPTION
**Pull request by GeckoEidechse**
As discussed in #233 saving persistent store was broken some time ago. Calling `save` explicitly  seems to resolve it.

For good measure, also bumped plugin-store version and updated pulled dependency as [described in their README](https://github.com/tauri-apps/plugins-workspace/tree/dev/plugins/store).

- Closes #233 
- Unblocks #182

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Need to do some testing to confirm still.

**Comment by GeckoEidechse** [comment]
Yeah that doesn't seem to fix #233

**Comment by GeckoEidechse** [comment]
Even trying to reduce tauri API version again does not resolve the issue T-T

**Comment by GeckoEidechse** [comment]
Still not fixed btw

**Comment by GeckoEidechse** [comment]
Fixed with 6b087b1448d3e86a04359a752e2cc6ae3b886cdd on Linux. Cannot test Windows atm.

File: src-vue/src/views/SettingsView.vue [hunk 1]
```diff
@@ -78,9 +78,10 @@ export default defineComponent({
             get(): boolean {
                 return this.$store.state.enableReleasesSwitch;
             },
-            set(value: boolean): void {
+            async set(value: boolean): Promise<void> {
```
Comment (GeckoEidechse) [inline src-vue/src/views/SettingsView.vue:81]: Uh, the `Promise` return value was introduced by running a quick fix action in vscode. Not sure if correct ^^"

**Comment by Alystrasz** [comment]
So basic issue was not saving store after inserting new keys?
I don't understand how persistence worked somehow while we didn't call `save`?

**Comment by GeckoEidechse** [comment]
> So basic issue was not saving store after inserting new keys? I don't understand how persistence worked somehow while we didn't call `save`?

So basically if you don't call `save()` it only saves persistence when exiting the application which was how we did saving so far. For some reason this broke at some point for reason unknown to me. Calling `save()` explicitly seems to be enough to "fix" it.
A proper fix would require investigating the issue upstream which is something I don't have the time/knowledge to do ^^"

File: src-vue/src/views/SettingsView.vue (hunk 1 above)
Comment (Alystrasz) [reply src-vue/src/views/SettingsView.vue:81]: Yeah it's correct

File: src-tauri/Cargo.toml [hunk 2]
```diff
@@ -43,7 +43,7 @@ sysinfo = "0.26.2"
 # HTTP requests
 reqwest = { version = "0.11", features = ["blocking"] }
 # Persistent store for settings
-tauri-plugin-store = { git = "https://github.com/tauri-apps/tauri-plugin-store", rev = "9bd993aa67766596638bbfd91e79a1bf8f632014" }
+tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }
```
Comment (Alystrasz) [inline src-tauri/Cargo.toml:46]: Could you point to a commit instead of a branch?

**Review by Alystrasz — COMMENTED** [review]
Apart from the comment, looks good; confirmed working on Windows.

File: src-tauri/Cargo.toml (hunk 2 above)
Comment (GeckoEidechse) [reply src-tauri/Cargo.toml]: Shouldn't really be necessary but given that the plugin store is still under active development it might be for the best.

Resolved in 22ac2cafd7fb5946a5ba99044572fb3316e59761

**Review by Alystrasz — APPROVED** [review]
